### ISSUE TITLE
All my charts are blank

### ISSUE THREAD

**Issue by smitpi** [qschweitzer/Powershell-HTML5-Reporting#3]
**Describe the bug**
All my charts are blank. The background shows ext., but no chart.

Not sure if I'm missing from the installation ext., But this looks like an awesome project! Thanks creating it.

**To Reproduce**
```
New-PWFRow -Content {
        New-PWFColumn -Content {
          New-PWFCard -BackgroundColor "#6d597a" -Content {
            New-PWFTitles -Size 3 -TitleText "Disks capacity" -LightMode -Center
            $DisksInfos =  (Get-Disk | Select-Object FriendlyName,@{Name='Size in GB'; Expression={[math]::Round(($_.Size/1GB),2)}})
            New-PWFChart -ChartValues $DisksInfos."Size in GB" -ChartLabels $DisksInfos.FriendlyName -ChartTitle "Disk Space in GB" -ChartType bar -LightMode -DontShowTitle
          }
        }
```

**Expected behavior**
To show data

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome and ms edge
 - Version latest
 - Powershell version 5.1 and 7

**Comment by qschweitzer** [comment]
Hi,
I don't know why Github does not notify me about your issue.
I will analyze it.
You have to know that I've pushed the last update on Powershell Gallery for the fist time today.
Install it with Install-Module POSHTML5

**Comment by qschweitzer** [comment]
Hi,

I try to reproduce your issue, first time issue appears, and the reason was: 
`Impossible to bind the argument to the "ChartValues" parameter, because it has the value Null.`

Next I tried to create manually the var before invoke all code, that works fine.
In another shell, no issue again...

Try the last version of the module as I said in my last reply, but clearly I think there is a real explains of what happens, I don't have it yet.
I'll investigate more than a time fore sure.
Thanks for using my project !

**Comment by smitpi** [comment]
Thanks. Its working after i updated the module. 

Thanks for your help!

And really an awesome project! Well done. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
